import pandas as pd
import numpy as np
from sklearn import ensemble, model_selection, inspection


data = pd.read_csv('basefile_V2.csv')

n_estimators = [int(x) for x in np.linspace(start=200, stop=2000, num=10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(10, 110, num=11)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

rf_random = model_selection.RandomizedSearchCV(estimator=ensemble.RandomForestRegressor(),
                                               param_distributions=random_grid,
                                               n_iter=200, cv=3, verbose=2, random_state=42,
                                               n_jobs=-1)

features = ['0_climbing_mtrs',
            '0_grad',
            '0_alt',
            '0_abs_grad',
            '0_max_grad',
            '0_max_grad_pos',
            '0_max_alt',
            '0_max_alt_pos',
            '0_min_alt',
            '0_min_alt_pos',
            '0_num_grad_sign_change',
            '0_perc_flat',
            '0_perc_descent',
            '0_perc_descent_steep',
            '0_perc_climb_shallow',
            '0_perc_climb_medium',
            '0_perc_climb_steep',
            '1_climbing_mtrs',
            '1_grad',
            '1_alt',
            '1_abs_grad',
            '1_max_grad',
            '1_max_grad_pos',
            '1_max_alt',
            '1_max_alt_pos',
            '1_min_alt',
            '1_min_alt_pos',
            '1_num_grad_sign_change',
            '1_perc_flat',
            '1_perc_descent',
            '1_perc_descent_steep',
            '1_perc_climb_shallow',
            '1_perc_climb_medium',
            '1_perc_climb_steep',
            '2_climbing_mtrs',
            '2_grad',
            '2_alt',
            '2_abs_grad',
            '2_max_grad',
            '2_max_grad_pos',
            '2_max_alt',
            '2_max_alt_pos',
            '2_min_alt',
            '2_min_alt_pos',
            '2_num_grad_sign_change',
            '2_perc_flat',
            '2_perc_descent',
            '2_perc_descent_steep',
            '2_perc_climb_shallow',
            '2_perc_climb_medium',
            '2_perc_climb_steep',
            '3_climbing_mtrs',
            '3_grad',
            '3_alt',
            '3_abs_grad',
            '3_max_grad',
            '3_max_grad_pos',
            '3_max_alt',
            '3_max_alt_pos',
            '3_min_alt',
            '3_min_alt_pos',
            '3_num_grad_sign_change',
            '3_perc_flat',
            '3_perc_descent',
            '3_perc_descent_steep',
            '3_perc_climb_shallow',
            '3_perc_climb_medium',
            '3_perc_climb_steep',
            '4_climbing_mtrs',
            '4_grad',
            '4_alt',
            '4_abs_grad',
            '4_max_grad',
            '4_max_grad_pos',
            '4_max_alt',
            '4_max_alt_pos',
            '4_min_alt',
            '4_min_alt_pos',
            '4_num_grad_sign_change',
            '4_perc_flat',
            '4_perc_descent',
            '4_perc_descent_steep',
            '4_perc_climb_shallow',
            '4_perc_climb_medium',
            '4_perc_climb_steep',
            '5_climbing_mtrs',
            '5_grad',
            '5_alt',
            '5_abs_grad',
            '5_max_grad',
            '5_max_grad_pos',
            '5_max_alt',
            '5_max_alt_pos',
            '5_min_alt',
            '5_min_alt_pos',
            '5_num_grad_sign_change',
            '5_perc_flat',
            '5_perc_descent',
            '5_perc_descent_steep',
            '5_perc_climb_shallow',
            '5_perc_climb_medium',
            '5_perc_climb_steep',
            '6_climbing_mtrs',
            '6_grad',
            '6_alt',
            '6_abs_grad',
            '6_max_grad',
            '6_max_grad_pos',
            '6_max_alt',
            '6_max_alt_pos',
            '6_min_alt',
            '6_min_alt_pos',
            '6_num_grad_sign_change',
            '6_perc_flat',
            '6_perc_descent',
            '6_perc_descent_steep',
            '6_perc_climb_shallow',
            '6_perc_climb_medium',
            '6_perc_climb_steep',
            '7_climbing_mtrs',
            '7_grad',
            '7_alt',
            '7_abs_grad',
            '7_max_grad',
            '7_max_grad_pos',
            '7_max_alt',
            '7_max_alt_pos',
            '7_min_alt',
            '7_min_alt_pos',
            '7_num_grad_sign_change',
            '7_perc_flat',
            '7_perc_descent',
            '7_perc_descent_steep',
            '7_perc_climb_shallow',
            '7_perc_climb_medium',
            '7_perc_climb_steep',
            '8_climbing_mtrs',
            '8_grad',
            '8_alt',
            '8_abs_grad',
            '8_max_grad',
            '8_max_grad_pos',
            '8_max_alt',
            '8_max_alt_pos',
            '8_min_alt',
            '8_min_alt_pos',
            '8_num_grad_sign_change',
            '8_perc_flat',
            '8_perc_descent',
            '8_perc_descent_steep',
            '8_perc_climb_shallow',
            '8_perc_climb_medium',
            '8_perc_climb_steep',
            '9_climbing_mtrs',
            '9_grad',
            '9_alt',
            '9_abs_grad',
            '9_max_grad',
            '9_max_grad_pos',
            '9_max_alt',
            '9_max_alt_pos',
            '9_min_alt',
            '9_min_alt_pos',
            '9_num_grad_sign_change',
            '9_perc_flat',
            '9_perc_descent',
            '9_perc_descent_steep',
            '9_perc_climb_shallow',
            '9_perc_climb_medium',
            '9_perc_climb_steep',
            '10_climbing_mtrs',
            '10_grad',
            '10_alt',
            '10_abs_grad',
            '10_max_grad',
            '10_max_grad_pos',
            '10_max_alt',
            '10_max_alt_pos',
            '10_min_alt',
            '10_min_alt_pos',
            '10_num_grad_sign_change',
            '10_perc_flat',
            '10_perc_descent',
            '10_perc_descent_steep',
            '10_perc_climb_shallow',
            '10_perc_climb_medium',
            '10_perc_climb_steep',
            '11_climbing_mtrs',
            '11_grad',
            '11_alt',
            '11_abs_grad',
            '11_max_grad',
            '11_max_grad_pos',
            '11_max_alt',
            '11_max_alt_pos',
            '11_min_alt',
            '11_min_alt_pos',
            '11_num_grad_sign_change',
            '11_perc_flat',
            '11_perc_descent',
            '11_perc_descent_steep',
            '11_perc_climb_shallow',
            '11_perc_climb_medium',
            '11_perc_climb_steep',
            '12_climbing_mtrs',
            '12_grad',
            '12_alt',
            '12_abs_grad',
            '12_max_grad',
            '12_max_grad_pos',
            '12_max_alt',
            '12_max_alt_pos',
            '12_min_alt',
            '12_min_alt_pos',
            '12_num_grad_sign_change',
            '12_perc_flat',
            '12_perc_descent',
            '12_perc_descent_steep',
            '12_perc_climb_shallow',
            '12_perc_climb_medium',
            '12_perc_climb_steep',
            '13_climbing_mtrs',
            '13_grad',
            '13_alt',
            '13_abs_grad',
            '13_max_grad',
            '13_max_grad_pos',
            '13_max_alt',
            '13_max_alt_pos',
            '13_min_alt',
            '13_min_alt_pos',
            '13_num_grad_sign_change',
            '13_perc_flat',
            '13_perc_descent',
            '13_perc_descent_steep',
            '13_perc_climb_shallow',
            '13_perc_climb_medium',
            '13_perc_climb_steep',
            '14_climbing_mtrs',
            '14_grad',
            '14_alt',
            '14_abs_grad',
            '14_max_grad',
            '14_max_grad_pos',
            '14_max_alt',
            '14_max_alt_pos',
            '14_min_alt',
            '14_min_alt_pos',
            '14_num_grad_sign_change',
            '14_perc_flat',
            '14_perc_descent',
            '14_perc_descent_steep',
            '14_perc_climb_shallow',
            '14_perc_climb_medium',
            '14_perc_climb_steep',
            'Distance',
            'vert',
            'rank',
            'qual',
            'date_#']

other_targets = ['Won how?']

for target in ['finish_time', 'group_size', 'next_gap',	'ave_spd']:

    X = data.loc[(data[target].notna()) & (data[target] != ',,'), features]
    y = data.loc[(data[target].notna()) & (data[target] != ',,'), target]

    rf_random.fit(X, y)

    rf = ensemble.RandomForestRegressor()
    rf.set_params(**rf_random.best_params_)
    rf.fit(X, y)

    result = inspection.permutation_importance(rf, X, y, n_repeats=30, random_state=42)

    pd.DataFrame({'feature': features,
                  'mean': result.importances_mean,
                  'std': result.importances_std}).sort_values(['mean']).to_csv(target+'_importance.csv', index=False)
